name: White CI/CD

on:
  workflow_dispatch:

jobs:

  # =========================
  # 1. Test
  # =========================
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18

        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: white_test_db

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U test_user -d white_test_db"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/white_test_db

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest


  # =========================
  # 2. Build & Push
  # =========================
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t mahmoudeng/white-backend:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push mahmoudeng/white-backend:${{ github.sha }}


  # =========================
  # 3. Deploy
  # =========================
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Server 1
        run: |
          ssh -i <(echo "${{ secrets.PROD_SERVER_1_SSH_KEY }}") \
            -o StrictHostKeyChecking=no \
            ${{ secrets.PROD_SERVER_1_USER }}@${{ secrets.PROD_SERVER_1_HOST }} << EOF

            cd ~/white

            export IMAGE_TAG=${{ github.sha }}

            docker compose pull
            docker compose up -d

          EOF

      - name: Deploy to Server 2
        run: |
          ssh -i <(echo "${{ secrets.PROD_SERVER_2_SSH_KEY }}") \
            -o StrictHostKeyChecking=no \
            ${{ secrets.PROD_SERVER_2_USER }}@${{ secrets.PROD_SERVER_2_HOST }} << EOF

            cd ~/white

            export IMAGE_TAG=${{ github.sha }}

            docker compose pull
            docker compose up -d

          EOF
